CREATE TABLE [dbo].[user_master]
(
	[id] INT NOT NULL IDENTITY(0,1),
	[name] NVARCHAR(200) NOT NULL,
	email NVARCHAR(200) NOT NULL,
	dob NVARCHAR(12) NULL,
	about NVARCHAR(2000) NULL,
	photo_url NVARCHAR(MAX) NULL,
	created_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_datetime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by NVARCHAR(200) NOT NULL,
	updated_by NVARCHAR(200) NOT NULL,
	CONSTRAINT pk_userid PRIMARY KEY (id) 

 )
